# Numpy

Numpy stands for Numerical Python.\
Numpy is used for doing mathematical computations.\
Numpy makes use of arrays rather than lists.\
Numpy arrays can also store multiple data types as python lists.

## Benefits on using arrays
   1.Memory efficient than lists\
   2.We can do broadcasting operations on numpy arrays.\
   3.Most of the other libraries(Scipy,Matplotlib,Pandas,Seaborn,Scikit Learn..) make use of these numpy arrays

In [93]:
#importing Numpy
import numpy as np

In [94]:
# making numpy arrays
arr=np.array([1,2,3,4,5])

In [95]:
arr

array([1, 2, 3, 4, 5])

In [96]:
arr.dtype # By dtype function,we get the data type of the elements 

dtype('int64')

In [97]:
type(arr) 

numpy.ndarray

Arrays can be of n-dimensional.\
Vectors are 1-dimensional arrays.\
Matrix is 2-dimensional numpy array.

In [98]:
arr.shape # Getting shape of arr

(5,)

In [99]:
# checking dimensions of arr 
#                      by using arr.ndim function    
print(f"Above defined array is of {arr.ndim} dimensions")

Above defined array is of 1 dimensions


In [100]:
# INDEXING 
#      Starts from 0 
arr[3] 

4

In [101]:
# NEGATIVE INDEXING
#       Last element index starts from -1
arr[-1]

5

In [102]:
# Creating a Matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [103]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
matrix.shape

(3, 3)

In [105]:
matrix.ndim # checking dimensions of matrix

2

In [106]:
matrix[1] # Here,we are printing 1st row

array([4, 5, 6])

In [107]:
matrix[1,2] # Getting element at 1st row,2nd column

6

# we can create data by using numpy

## Using arange function

np.arange(start,stop,step)

In [108]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

## Using zeros function

zeros(shape,dtype=float)

In [110]:
np.zeros(3)

array([0., 0., 0.])

In [111]:
np.zeros((3,1)) # here default dtype is float

array([[0.],
       [0.],
       [0.]])

In [112]:
np.zeros((3,1),dtype=int) # here dtype is int

array([[0],
       [0],
       [0]])

## As same as zeros function in numpy,there is ones function
    That creates matrices of specified shape,having all elements as 1

In [113]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

## Using eye function
    Returns identity matrix of specified shape

In [114]:
np.eye(3) # Here,we got 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Slicing


In [115]:
arr1=np.arange(10)

In [116]:
arr1[0:6] # Here,we got elements from index postion 0 to index position 5 NOT including index 6

array([0, 1, 2, 3, 4, 5])

In [117]:
arr1[1:] # Here,we got elements from index 1 to last index

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr1[:] # Here,we got all elements in list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
arr1[:4] # Here,we got elements upto index 3 NOT including 3

array([0, 1, 2, 3])

In [120]:
# arr[start:end:step]
arr1[0:8:2]

array([0, 2, 4, 6])

In [121]:
# SLICING USING NEGATIVE INDEXING
arr1[-5:-1]

array([5, 6, 7, 8])

## Using linspace funtion
   This function returns evenly spaced numbers over a specified interval

In [122]:
np.linspace(0,100,5) # we got 5 numbers in between 0 and 100,having same difference between them

array([  0.,  25.,  50.,  75., 100.])

## Numpy-Random Module

Random number does NOT mean a different number every time.We cannot predict that number logically. 

In [123]:
np.random.rand(2,1) # We got random values of shape 2x1 

array([[0.06863852],
       [0.07533272]])

## np.random.randint
np.random.randint(low,high,size)

In [124]:
np.random.randint(low=0,high=20,size=4) # Here,we got 4 random numbers in between 0 and 20

array([17, 11, 17, 10])

## np.random.randn

In [125]:
np.random.randn(4,2) # Here,we also get some negative numbers

array([[-0.55933648, -0.08687402],
       [-0.23741198, -1.36069489],
       [-0.16085056, -0.34757393],
       [-0.09708836,  0.19831304]])

## Difference between np.random.rand and np.random.randn
   numpy.random.randn generates samples from the normal distribution where as \
   numpy.random.rand generates samples in range [0,1]

## Numpy Seed
    Seed is used to intialize random number generator.
    By using it,we get same set of nmubers every time.

#### Here,condition is we have to set the seed and produce random numbers in SAME CELL

In [126]:
np.random.seed(31)
np.random.randint(low=0,high=100,size=10) # First time printing random numbers

array([82, 87, 16, 98, 23, 58, 28, 93, 92, 42])

In [127]:
np.random.seed(31)
np.random.randint(low=0,high=100,size=10) # Second time printing random numbers,
                                          # We got same random numbers as we used same SEED

array([82, 87, 16, 98, 23, 58, 28, 93, 92, 42])

## Getting maximum and minimum values in a numpy array
    By using max and min functions

In [128]:
arr

array([1, 2, 3, 4, 5])

In [129]:
print(f'maximum element in arr is {arr.max()}')
print(f'maximum element in arr is {arr.min()}')

maximum element in arr is 5
maximum element in arr is 1


### we can also get index of maximum and minimum elements of array
    By using argmax() and argmin() functions

In [130]:
print(f"Maximum element is at index {arr.argmax()}")
print(f"Minimum element is at index {arr.argmin()}")

Maximum element is at index 4
Minimum element is at index 0


### We can run small queries like 
    Are array elements greater than a particular number?.. 

In [131]:
new_arr=np.arange(1,50,4)
new_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [132]:
new_arr > 10 # It returns a boolean array 

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [133]:
bool_array= (new_arr > 10)
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [134]:
bool_array.dtype

dtype('bool')

In [135]:
# To get those elements which satisfy the condition
new_arr[bool_array]

array([13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [136]:
# Simple way to do it is
new_arr[new_arr > 10]

array([13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

## Arithmetic operations on numpy arrays

In [137]:
arr

array([1, 2, 3, 4, 5])

In [138]:
arr + 1 # Here,each element get added with 1(scalar),.like that we can do multiplication,subtraction,division..

array([2, 3, 4, 5, 6])

In [139]:
arr + arr # Here,2 arrays get added,.like that we can add n number of different or same arrays

array([ 2,  4,  6,  8, 10])

In [140]:
arr ** 2 # Exponentation 

array([ 1,  4,  9, 16, 25])

## Some of the statistical functions in numpy

In [141]:
test_array=np.array([5,8,2,4,9,18,31,30,35,87,99])

In [142]:
# Getting MEAN of array
test_array.mean()

29.818181818181817

In [143]:
# Getting MEDIAN of array
np.median(test_array) 

18.0

In [144]:
# Getting SUM of all elements in array
test_array.sum()

328

### Standard Deviation
    Standard Deviation is a measure of the amount of variation or dispersion of a set of values.
    A low standard deviation indicates that the values tend to be close to the mean of the elements set.
    A high standard deviation indicates that the values are spread out over a wider range.

In [145]:
# Getting STANDARD DEVIATION of the array
test_array.std()

31.8941949172806

### Variance is sqaured value of Standard Deviation

In [146]:
# Getting VARIANCE of the array
test_array.var()

1017.2396694214876

In [147]:
test_array.std() ** 2

1017.2396694214877